### ISSUE TITLE
Update style guide index.html template to include drupal.init.js after drupal.js

### ISSUE THREAD

**Issue by erichuffman-mc** [mediacurrent/theme_generator_8#10]
As of Drupal v8.3.0 the domready event has been split from the drupal.js file, so if using the theme builder in a environment that's running Drupal 8.3.0 or later then any js that relies on Drupal behaviors will not work.

See: https://www.drupal.org/node/2830647

**Comment by zhawkins** [comment]
Fixed via #13. Thanks!
