### ISSUE TITLE
Theme requires description

### ISSUE THREAD

**Issue by kbasarab** [mediacurrent/theme_generator_8#11]
When a description is not entered during the generation no description is given next to the key in the theme.info.yml file. This throws an error on admin/appearance. 

The following error is thrown:
InvalidArgumentException: $string ("") must be a string. in Drupal\Core\StringTranslation\TranslatableMarkup->__construct() (line 140 of core/lib/Drupal/Core/StringTranslation/TranslatableMarkup.php).

Adding a description fixes the issue or removing the null description key from the info.yml file.

**Comment by zhawkins** [comment]
Fixed via #13 Thanks!
