### ISSUE TITLE
Adding scss processing to pattern-scaffolding.css

### ISSUE THREAD

**Issue by Tregonia** [mediacurrent/theme_generator_8#114]
Quite often, the styleguide needs to process variables for the theme. This PR can add this functionality. The implementation is at a base level, and can be expanded.

**Comment by Tregonia** [comment]
Created a PR to implement the theme processing.
https://github.com/mediacurrent/theme_generator_8/pull/115

Included is an update to a typo in the readme, removal of a reference to an old client, and updating comments

**Comment by mariohernandez** [comment]
Can this issue be closed now, @Tregonia ?

**Comment by mariohernandez** [comment]
PR has already been merged.  Closing issue.
