### ISSUE TITLE
Include option to set version of node for theme.

### ISSUE THREAD

**Issue by Tregonia** [mediacurrent/theme_generator_8#14]
The readme includes all the required information for creating a .nvmrc file of the most current version of node for the project. However, this is still a post process we have to do later.

Since the generator is already asking the user questions, is it posible to ask a question to which version of node the them should use. An option for "most current" could still be included as a default.

**Comment by mariohernandez** [comment]
Closing issue.  If creating a new theme, it makes sense to use latest stable version of node.  It's uncertain what issues we could run into if allowed to run older versions of node.
