### ISSUE TITLE
Spacing of code in gulpfile.js

### ISSUE THREAD

**Issue by Tregonia** [mediacurrent/theme_generator_8#19]
Looking through the gulpfile.js file, it appears that there are instances where a blank line should exist to follow normal standards.

After Line 29
After Line 74
After Line 89
After Line 162 (indention is off)
After Line 171

https://github.com/mediacurrent/theme_generator_8/blob/master/generators/app/templates/_gulpfile.js

**Comment by mariohernandez** [comment]
With latest updates to the theme generator, the Gulpfile.js has been updated and the issues above no longer apply.
