### ISSUE TITLE
breakpoints.yml file seems to break theme

### ISSUE THREAD

**Issue by cehfisher** [mediacurrent/theme_generator_8#2]
I'm using DrupalVM and running the theme generator and adding components, whatnot, and all works well when viewing the style guide. But when I set the theme in the UI to the newly generated theme, the website breaks and give the message: `The website encountered an unexpected error. Please try again later.` This happens regardless of what options I choose in the initial generator build. After a lot of trial and error, removing the `breakpoints.yml` resolves my issue. Not sure if this is just an issue with my local, but something to look into.

**Comment by zhawkins** [comment]
Ah good looking out. I'll check it out. It may be that it's an empty file.

**Comment by zhawkins** [comment]
Thanks for the issue Carie.  #5 should hopefully fix it for you. 👍

**Comment by cehfisher** [comment]
Just confirming that this issue seems to be fixed. I spun up a new site over the weekend and did not encounter the same issue. thanks for the fix!
