### ISSUE TITLE
Style guide generating problem

### ISSUE THREAD

**Issue by IWD-Lab** [mediacurrent/theme_generator_8#20]
Could you help with the issue?
I have errors during generating new style-guide for my theme.
`npx -p yo -p generator-mc-d8-theme -c 'yo mc-d8-theme:kss-style-guide "My Awesome Theme Guide" "my_awesome_theme_guide"'`

```
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN ajv-keywords@2.1.0 requires a peer of ajv@>=5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN my_awesome_theme@1.0.0 No repository field.
npm WARN my_awesome_theme@1.0.0 No license field.

update	gulp-concat	2.6.1	node_modules/gulp-concat	2.6.1
update	gulp-order	1.1.1	node_modules/gulp-order	1.1.1
update	kss	3.0.0-beta.18	node_modules/kss	3.0.0-beta.18
```

**Comment by zhawkins** [comment]
What version of node are you using? I'll try it out.

**Comment by IWD-Lab** [comment]
I updated the version of npm. My macOS is Sierra v.10.12.6. 
I use node v9.2.0 (npm v5.5.1)

Now I have:
...
Created a new JavaScript behavior named sample-list.
-----------------------------------------
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN my_awesome_theme@1.0.0 No repository field.
npm WARN my_awesome_theme@1.0.0 No license field.

+ breakpoint-sass@2.7.1
+ singularitygs@1.8.0
added 2 packages in 0.528s
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated express@2.5.11: express 2.x series is deprecated
npm WARN deprecated connect@1.9.2: connect 1.x series is deprecated
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

> fsevents@1.1.3 install /Users/mac/Documents/Server/www/d8/themes/custom/my_awesome_theme/node_modules/fsevents
> node install

[fsevents] Success: "/Users/mac/Documents/Server/www/d8/themes/custom/my_awesome_theme/node_modules/fsevents/lib/binding/Release/node-v59-darwin-x64/fse.node" is installed via remote

> node-sass@4.7.2 install /Users/mac/Documents/Server/www/d8/themes/custom/my_awesome_theme/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.7.2/darwin-x64-59_binding.node
Download complete░░⸩ ⠋ :
Binary saved to /Users/mac/Documents/Server/www/d8/themes/custom/my_awesome_theme/node_modules/node-sass/vendor/darwin-x64-59/binding.node
Caching binary to /Users/mac/.npm/node-sass/4.7.2/darwin-x64-59_binding.node

> node-sass@4.7.2 postinstall /Users/mac/Documents/Server/www/d8/themes/custom/my_awesome_theme/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/mac/Documents/Server/www/d8/themes/custom/my_awesome_theme/node_modules/node-sass/vendor/darwin-x64-59/binding.node
Testing binary
Binary is fine

> gifsicle@3.0.4 postinstall /Users/mac/Documents/Server/www/d8/themes/custom/my_awesome_theme/node_modules/gifsicle
> node lib/install.js

  ✔ gifsicle pre-build test passed successfully

> jpegtran-bin@3.2.0 postinstall /Users/mac/Documents/Server/www/d8/themes/custom/my_awesome_theme/node_modules/jpegtran-bin
> node lib/install.js

  ✔ jpegtran pre-build test passed successfully

> optipng-bin@3.1.4 postinstall /Users/mac/Documents/Server/www/d8/themes/custom/my_awesome_theme/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN my_awesome_theme@1.0.0 No repository field.
npm WARN my_awesome_theme@1.0.0 No license field.

added 1118 packages in 23.806s
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN my_awesome_theme@1.0.0 No repository field.
npm WARN my_awesome_theme@1.0.0 No license field.

+ kss@3.0.0-beta.18
+ gulp-order@1.1.1
+ gulp-concat@2.6.1
added 36 packages in 8.842s
☠️  NOTE: Your new generated theme contains a fair bit of boilerplate code.
   This is by design. If you don't need it PLEASE delete it.
   You can always rerun the generator some other time in a different directory
   and copy over what you're missing.
#YOLO 🚀

**Comment by mariohernandez** [comment]
This issue is being closed for lack of activity and with latest version of the Theme Generator the node version in question is no longer relevant.
