### ISSUE TITLE
{% include '@themename/....' } dosen't work from KSS-node version 3.0.0-beta.16

### ISSUE THREAD

**Issue by marceldobrica** [mediacurrent/theme_generator_8#25]
Testing it I have found that include works ok until kss version 3.0.0-beta.16 (including icons)... next kss version is 3.0.0.-beta.19 doesn't work anymore...

Until someone founds the bug... we may use your theme generator replacing kss version in package.json, from "^3.0.0-beta.23", to "3.0.0-beta.16" deleting lock and re-run npm install.

**Comment by marceldobrica** [comment]
I have wrote same issue for kss-node and I get the solution https://github.com/kss-node/kss-node/issues/509#issuecomment-420624135
I have added twig in dependencies after kss and now I'm happy again.

**Comment by mariohernandez** [comment]
Add the following to your `package.json`'s dependencies section to fix this issue:
```
  "devDependencies": {
    "kss": "^3.0.0-beta.23",
    "twig": "RobLoach/twig.js#compile"
  }
```

- Then delete **node_modules** and **package-lock.json**
- Run `npm install`

**Comment by marceldobrica** [comment]
In media current theme generator, now with Twig 1.13.0 svg icons are imported converting tags as htmlentities...: < is converted in &lt; and so on...
so is still better to use 
"devDependencies": {
    "kss": "3.0.0-beta.23",
    "twig": "RobLoach/twig.js#compile"
  }

**Comment by marceldobrica** [comment]
Starting from KSS beta.25 it works again.
