### ISSUE TITLE
Namespace for KSS breaks on Windows

### ISSUE THREAD

**Issue by senhduong** [mediacurrent/theme_generator_8#30]
Check out [this issue](https://github.com/kss-node/kss-node/issues/514#issue-376521887) on KSS Node for background.

The issue is line 29 on styleguide.js:
namespace: '<%= themeName %>:' + dirname + '/src/components/'

On Windows, the above would produce: 
'themename:C:\folder/src/components' 

On KSS, the above would produce "C" as the namespace because it's splitting that line by the ":" delimiter and taking the second element as the path.

**Comment by mariohernandez** [comment]
Closing issue as the latest version of the Theme Generator no longer supports KSS Node.  The generator now uses Pattern Lab.
