### ISSUE TITLE
Missing layout directory

### ISSUE THREAD

**Issue by Tregonia** [mediacurrent/theme_generator_8#4]
These items in the gulpfile are looking for a `/layout` directory that does not exist in the theme on inital creation. You end up firing up a new theme, running the build, and have errors from the start as a result. Adding the `/layout` empty directory resolves the issue.

    // Watch all my sass files and compile sass if a file changes.
    gulp.watch(
            './src/{global,layout,components}/**/*.scss',
            ['watch:sass']
    );
    
    // Watch all my JS files and compile if a file changes.
    gulp.watch([
      './src/{global,layout,components}/**/*.js'
    ], ['lint:js', 'compile:js']);
    
    // Watch all my twig files and rebuild the style guide if a file changes.
    gulp.watch(
            './src/{layout,components}/**/*.twig',
            ['watch:styleguide']
    );

This is the error that is in the terminal on initial `npm run build`

    { Error: ENOENT: no such file or directory, scandir '/mytheme/src/layout'
      cause:
      { Error: ENOENT: no such file or directory, scandir '/mytheme/src/layout'
        errno: -2,
                code: 'ENOENT',
              syscall: 'scandir',
              path: '/mytheme/src/layout' },
      isOperational: true,
              errno: -2,
              code: 'ENOENT',
              syscall: 'scandir',
              path: '/mytheme/src/layout' }
    [09:26:14] 'styleguide' errored after 32 ms
            [09:26:14] Error: ENOENT: no such file or directory, scandir '/mytheme/src/layout'
            [09:26:14] 'default' errored after 112 ms
            [09:26:14] Error in plugin 'run-sequence(styleguide)'
    Message:
            ENOENT: no such file or directory, scandir '/mytheme/src/layout'
    Details:
            cause: Error: ENOENT: no such file or directory, scandir '/mytheme/src/layout'
    isOperational: true
    errno: -2
    code: ENOENT
    syscall: scandir
    path: /mytheme/src/layout
    Stack:
            Error: ENOENT: no such file or directory, scandir '/mytheme/src/layout'

**Comment by zhawkins** [comment]
Thanks for the issue Tim. I've fixed the error in #5 . 👍
