### ISSUE TITLE
Watch command does not trigger on changes to SVGs

### ISSUE THREAD

**Issue by Tregonia** [mediacurrent/theme_generator_8#53]
Updating the markup of an `.svg` file does not trigger processing of the image tools.

### To reproduce

1. Start the watch process with `$ npm run watch` and keep an eye on it
2. Edit any SVG that was output from [the icon component](https://github.com/mediacurrent/theme_generator_8/tree/master/generators/app/templates/_helper-components/icons/assets) 
3. Change `fill`, `stroke`, `class`, or any attribute

When the change to the files are saved, the watch process does not recognize the change, and does not update anything in the styleguide. As such, updates to icons requires a one-to-one build command for each icon update to review changes.

**Comment by Tregonia** [comment]
Updated the watch command to watch images and SVGs for triggers in the build.
https://github.com/mediacurrent/theme_generator_8/pull/56

**Comment by zhawkins** [comment]
Thanks Tim! Merged.
