### ISSUE TITLE
Update starter components to include MD files for documentation

### ISSUE THREAD

**Issue by Tregonia** [mediacurrent/theme_generator_8#58]
The existing setup does not include Markdown files that are used for documenting Patterns. Starter components can include a `.md` file to illustrate how this can be implemented.

Task
* Update patterns to include `.md` files that include documentation for Pattern.

**Comment by mariohernandez** [comment]
Hey @Tregonia could you provide initial markdown files for the components?  I feel most components will be refactored to an extend when used in a new custom theme and the markdown file may become obsolete or out of sync with the new structure of the component.  Should we keep this open?

**Comment by rlahoda** [comment]
I think this can be combined with the updated pattern of using markdown files for hiding files instead of the underscore since the underscore is being depreciated so we can create the markdown files for those initially to hide and start adding descriptions and helpful text to them as we continue

**Comment by mariohernandez** [comment]
The only pattern in which we are using underscore is the `_icons-macro.twig`.  Can't remember if I already updated it to the new way of hiding it.
