### ISSUE TITLE
ESLint Structure

### ISSUE THREAD

**Issue by graysonhicks** [mediacurrent/theme_generator_8#62]
Create a `mediacurrent/recommended` eslint config to handle vanilla JS standards.  This could then be installed and extended in the theme generator.

``` 
"extends": [
    "plugin:mediacurrent/recommended"
  ]
```

A React config should also be created as `mediacurrent/jsx` that could then be extended in theme generator projects that need React coverage, or on standalone React project as well.

Here is the documentation on creating a shareable/published eslint config:
https://eslint.org/docs/developer-guide/shareable-configs

**Comment by mariohernandez** [comment]
This is a nice-to-have.  Closing for now.
