### ISSUE TITLE
Remove the `========` comments from Sass files

### ISSUE THREAD

**Issue by zhawkins** [mediacurrent/theme_generator_8#65]
GrumPHP throws an error for `======` code because it's part of how git conflicts are denoted. We're using that for SCSS comments in Sass files. No reason we can't update those comments to not use `========`. 

https://github.com/mediacurrent/theme_generator_8/blob/master/generators/app/templates/_src/patterns/global/global.scss

**Comment by mariohernandez** [comment]
[PR](https://github.com/mediacurrent/theme_generator_8/pull/70) has been created for this.

**Comment by Tregonia** [comment]
Issue has been resolved https://github.com/mediacurrent/theme_generator_8/commit/5c5116f7fc985cc5590c5dbf7eeb0cb1b7194c39
