### ISSUE TITLE
Wrong closing tag in hero.twig

### ISSUE THREAD

**Issue by JEManndy** [mediacurrent/theme_generator_8#66]
After installing (`npm create yo mc-d8-theme`) :
In directory `src/patterns/components/hero` :
hero.twig begins (after `attach_library`) with a `<div>` which is closed  with `</section>`
The first `<div` was presumably intended to be `<section`.

**Comment by mariohernandez** [comment]
Thank you for submitting this issue, @JEManndy.  We have [created a PR](https://github.com/mediacurrent/theme_generator_8/pull/69) to make this correction.

**Comment by Tregonia** [comment]
This is integrated in https://github.com/mediacurrent/theme_generator_8/commit/c0c10d46a25e1e888cad50e763da0ece21dbbd55
