### ISSUE TITLE
Add Pattern Lab Drupal plugin

### ISSUE THREAD

**Issue by damienmckenna** [mediacurrent/theme_generator_8#79]
Given that this system is for building Drupal themes that use Pattern Lab, it would make sense to add the official Pattern Lab Drupal components:
* https://github.com/pattern-lab/plugin-drupal-twig-components

**Comment by mariohernandez** [comment]
We no longer use the Twig edition of Pattern Lab.  We now use the Node edition which uses Twig-php engine and it has better compatibility with Drupal's Twig.  The Twig edition of PL actually uses Twig.js which has limitation and compatibility issues with Drupal.
