### ISSUE TITLE
Base CSS for Drupal Tabs

### ISSUE THREAD

**Issue by kbasarab** [mediacurrent/theme_generator_8#8]
On each site the local user tasks are unstyled and require a task to set these up for each individual site. Base styles should be included to make these appear in a decent way either in the admin toolbar or across the page. 

Unstyled Example: http://take.ms/IOCqj

**Comment by mariohernandez** [comment]
I have written styles for drupal tabs that can be easily integrated here.  I'll work on that.  Thanks @kbasarab.

**Comment by mariohernandez** [comment]
Closing issue as Drupal tabs are now an optional feature of the latest theme generator.
